# Generated by Django 5.2.3 on 2026-02-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='icon',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
