# Generated by Django 5.2.3 on 2026-02-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_competence_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=80)),
                ('titre', models.CharField(max_length=160)),
                ('lieu', models.CharField(max_length=160)),
                ('localisation', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Parcours',
                'verbose_name_plural': 'Parcours',
                'ordering': ['ordre', '-id'],
            },
        ),
    ]
